github_dwh:
  target: prod
  outputs:
    prod:
      type: clickhouse
      host: 127.0.0.1
      port: 8123
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      schema: "{{ env_var('CLICKHOUSE_ANALYTICS_DATABASE') }}"
      secure: false
      threads: 4
